name: Build

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.ipp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.ipp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/build.yml'

jobs:
  Build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Windows-MSVC/2019/x64/Release",
            os: windows-2019,
            config: Release,
          }
          - {
            name: "MacOSX/10.15/x64/Release",
            os: macos-10.15,
            config: Release,
          }

    steps:
    - uses: actions/checkout@v2

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v7
      with:
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
        vcpkgArguments: 'doctest grpc[codegen] boost-coroutine boost-core boost-intrusive boost-lockfree boost-asio boost-interprocess boost-thread'
        vcpkgGitCommitId: 1909fbc4eb8ef30017a79dce50c0f232d149a051 # Sep 11, 2021

    # - name: Configure CMake
    #   run: |
    #     cmake -B ${{ github.workspace }}/build \
    #       -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake \
    #       -DVCPKG_MANIFEST_MODE=off \
    #       -DCMAKE_BUILD_TYPE=${{ matrix.config.config }} \
    #       -DASIO_GRPC_BUILD_TESTS=on \
    #       -DASIO_GRPC_DISCOVER_TESTS=on \
    #       -DASIO_GRPC_BUILD_EXAMPLES=on \
    #       -DASIO_GRPC_BUILD_BENCHMARK=on \
    #       -DCMAKE_DISABLE_PRECOMPILE_HEADERS=on

    # - name: Build
    #   run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.config.config }} --parallel 2

    # - name: Test
    #   working-directory: ${{ github.workspace }}/build
    #   run: ctest -C ${{ matrix.config.config }} -T test -j 2 --output-on-failure --timeout 200
