name: Build

on:
  push:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.ipp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/build.yml'
      - 'sonar-project.properties'
      - 'vcpkg.json'
      - 'CMakePresets.json'
  pull_request:
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.ipp'
      - '**.cmake'
      - '**/CMakeLists.txt'
      - '.github/workflows/build.yml'
      - 'sonar-project.properties'
      - 'vcpkg.json'
      - 'CMakePresets.json'

env:
  VCPKG_VERSION: '70a7074c685516fed36da7befb3898821b1425ed' # Mar 21, 2022
  CMAKE_ARGS: '-DCMAKE_BUILD_TYPE=Release'
  CTEST_ARGS: '-T test --output-on-failure --timeout 200 --no-tests=error --parallel 8'

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: 'Windows/2022/MSVC-19.31',
            os: windows-2022,
            triplet: 'x64-windows-release',
            cmake-extra-args: '',
            parallel: 1,
          }
          - {
            name: 'MacOSX/11/AppleClang-13.0.0.13000029',
            os: macos-11,
            triplet: 'x64-osx-release',
            cmake-extra-args: '-DASIO_GRPC_USE_BOOST_CONTAINER=on',
            parallel: 3,
          }

    steps:
    - uses: actions/checkout@v2

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
        vcpkgGitCommitId: '${{ env.VCPKG_VERSION }}'
        vcpkgJsonGlob: 'vcpkg.json'
        appendedCacheKey: 'v1'

    - name: Run vcpkg
      run: |
        ${{ env.VCPKG_ROOT }}/vcpkg install --recurse --clean-after-build --triplet ${{ matrix.config.triplet }} --host-triplet ${{ matrix.config.triplet }} --overlay-ports=${{ github.workspace }}/deps --overlay-triplets=${{ github.workspace }}/.github/vcpkg &&
        ${{ env.VCPKG_ROOT }}/vcpkg integrate install

    - name: Configure CMake
      run: cmake --preset default ${{ matrix.config.cmake-extra-args }} ${{ env.CMAKE_ARGS }}

    - name: Build
      run: cmake --build --preset default --config Release --parallel ${{ matrix.config.parallel }}

    - name: Test
      run: ctest --preset default --config Release


  multi-gcc-build:
    name: 'Ubuntu/20.04/GCC-9.3.0,10.3.0,11.1.0'
    runs-on: ubuntu-20.04
    env:
      CMAKE_EXTRA_ARGS: '-DASIO_GRPC_ENABLE_IO_URING_EXAMPLES=off'

    steps:
    - name: Install GCC 11 and gcovr
      run: |
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test &&\
        sudo apt-get install g++-11 &&\
        sudo apt-get install gcovr

    - name: Make gcc-9 default compiler
      run: |
        sudo update-alternatives --install /usr/bin/cc cc $(which gcc-9) 50 &&\
        sudo update-alternatives --set cc $(which gcc-9) &&\
        sudo update-alternatives --install /usr/bin/c++ c++ $(which g++-9) 50 &&\
        sudo update-alternatives --set c++ $(which g++-9)  &&\
        sudo update-alternatives --install /usr/bin/cpp cpp $(which g++-9) 50 &&\
        sudo update-alternatives --set cpp $(which g++-9)

    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of sonarsource reporting
        fetch-depth: 0

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
        vcpkgGitCommitId: '${{ env.VCPKG_VERSION }}'
        vcpkgJsonGlob: 'vcpkg.json'
        appendedCacheKey: 'v1'

    - name: Run vcpkg
      run: |
        ${{ env.VCPKG_ROOT }}/vcpkg install --recurse --clean-after-build --overlay-ports=${{ github.workspace }}/deps &&
        ${{ env.VCPKG_ROOT }}/vcpkg integrate install

    - name: GCC 9 Configure CMake
      run: cmake --preset default -B ${{ github.workspace }}/build-9 -DCMAKE_CXX_COMPILER=$(which g++-9) ${{ env.CMAKE_EXTRA_ARGS }} ${{ env.CMAKE_ARGS }}

    - name: GCC 9 Build
      run: cmake --build ${{ github.workspace }}/build-9 --config Release --parallel $(nproc)

    - name: GCC 9 Test
      run: ctest ${{ env.CTEST_ARGS }} --test-dir ${{ github.workspace }}/build-9 --config Release

    - name: GCC 10 Configure CMake
      run: cmake --preset default -B ${{ github.workspace }}/build-10 -DCMAKE_CXX_COMPILER=$(which g++-10) -DCMAKE_EXPORT_COMPILE_COMMANDS=on -DASIO_GRPC_TEST_COVERAGE=on -DASIO_GRPC_GCOV_PROGRAM=$(which gcov-10) -DASIO_GRPC_COVERAGE_OUTPUT_FILE=${{ github.workspace }}/build-10/sonarqube-coverage.xml ${{ env.CMAKE_EXTRA_ARGS }} ${{ env.CMAKE_ARGS }} -DCMAKE_BUILD_TYPE=Debug

    - name: GCC 10 Build
      run: cmake --build ${{ github.workspace }}/build-10 --config Debug --parallel $(nproc)

    - name: GCC 10 Test
      run: ctest ${{ env.CTEST_ARGS }} --test-dir ${{ github.workspace }}/build-10 --config Debug

    - name: GCC 10 Coverage
      run: cmake --build ${{ github.workspace }}/build-10 --config Debug --target asio-grpc-test-coverage

    - name: Download sonar-scanner
      uses: warchant/setup-sonar-scanner@v3
      with:
        version: 4.6.2.2472

    - name: Run sonar-scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        sonar-scanner \
          -Dsonar.cfamily.compile-commands=${{ github.workspace }}/build-10/compile_commands.json \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.coverageReportPaths=${{ github.workspace }}/build-10/sonarqube-coverage.xml

    - name: GCC 11 Configure CMake
      run: cmake --preset default -B ${{ github.workspace }}/build-11 -DCMAKE_CXX_COMPILER=$(which g++-11) ${{ env.CMAKE_EXTRA_ARGS }} ${{ env.CMAKE_ARGS }}

    - name: GCC 11 Build
      run: cmake --build ${{ github.workspace }}/build-11 --config Release --parallel $(nproc)

    - name: GCC 11 Test
      run: ctest ${{ env.CTEST_ARGS }} --test-dir ${{ github.workspace }}/build-11 --config Release


  multi-clang-build:
    name: 'Ubuntu/20.04/Clang-10.0.0,11.0.0,12.0.0'
    runs-on: ubuntu-20.04
    env:
      CMAKE_EXTRA_ARGS: '-DASIO_GRPC_ENABLE_IO_URING_EXAMPLES=off -DASIO_GRPC_USE_BOOST_CONTAINER=on "-DCMAKE_CXX_FLAGS=-stdlib=libc++ -stdlib++-isystem /usr/lib/llvm-10/include/c++/v1/"'

    steps:
    - name: Make clang-10 default compiler
      run: |
        sudo update-alternatives --install /usr/bin/cc cc $(which clang-10) 50 &&\
        sudo update-alternatives --set cc $(which clang-10) &&\
        sudo update-alternatives --install /usr/bin/c++ c++ $(which clang++-10) 50 &&\
        sudo update-alternatives --set c++ $(which clang++-10)  &&\
        sudo update-alternatives --install /usr/bin/cpp cpp $(which clang++-10) 50 &&\
        sudo update-alternatives --set cpp $(which clang++-10)

    - uses: actions/checkout@v2

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ runner.workspace }}/vcpkg'
        vcpkgGitCommitId: '${{ env.VCPKG_VERSION }}'
        vcpkgJsonGlob: 'vcpkg.json'
        appendedCacheKey: 'clang-v1'

    - name: Run vcpkg
      run: |
        ${{ env.VCPKG_ROOT }}/vcpkg install --recurse --clean-after-build --triplet x64-linux-clang-release --host-triplet x64-linux-clang-release --overlay-ports=${{ github.workspace }}/deps --overlay-triplets=${{ github.workspace }}/.github/vcpkg &&
        ${{ env.VCPKG_ROOT }}/vcpkg integrate install

    - name: Clang 10 Configure CMake
      run: cmake --preset default -B ${{ github.workspace }}/build-10 -DCMAKE_CXX_COMPILER=$(which clang++-10) ${{ env.CMAKE_EXTRA_ARGS }} ${{ env.CMAKE_ARGS }}

    - name: Clang 10 Build
      run: cmake --build ${{ github.workspace }}/build-10 --config Release --parallel $(nproc)

    - name: Clang 10 Test
      run: ctest ${{ env.CTEST_ARGS }} --test-dir ${{ github.workspace }}/build-10 --config Release

    - name: Clang 11 Configure CMake
      run: cmake --preset default -B ${{ github.workspace }}/build-11 -DCMAKE_CXX_COMPILER=$(which clang++-11) ${{ env.CMAKE_EXTRA_ARGS }} ${{ env.CMAKE_ARGS }}

    - name: Clang 11 Build
      run: cmake --build ${{ github.workspace }}/build-11 --config Release --parallel $(nproc)

    - name: Clang 11 Test
      run: ctest ${{ env.CTEST_ARGS }} --test-dir ${{ github.workspace }}/build-11 --config Release

    - name: Download doxygen
      working-directory: ${{ runner.workspace }}
      run: |
        cmake -E make_directory doxygen &&\
        cd doxygen &&\
        wget --quiet https://www.doxygen.nl/files/doxygen-1.9.3.linux.bin.tar.gz &&\
        tar xf doxygen-1.9.3.linux.bin.tar.gz --strip-components=1

    - name: Clang 12 Configure CMake
      run: cmake --preset default -B ${{ github.workspace }}/build-12 -DCMAKE_CXX_COMPILER=$(which clang++-12) -DDOXYGEN_EXECUTABLE=${{ runner.workspace }}/doxygen/bin/doxygen ${{ env.CMAKE_EXTRA_ARGS }} ${{ env.CMAKE_ARGS }}

    - name: Clang 12 Build
      run: cmake --build ${{ github.workspace }}/build-12 --config Release --parallel $(nproc)

    - name: Clang 12 Test
      run: ctest ${{ env.CTEST_ARGS }} --test-dir ${{ github.workspace }}/build-12 --config Release

    - name: Run doxygen
      run: |
        cmake -E rm -r ${{ github.workspace }}/docs &&\
        cmake --build ${{ github.workspace }}/build-12 --config Release --target asio-grpc-doxygen

    - name: Push doxygen changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/* || echo "nothing to commit"
        git commit -m "Re-generate Github Pages" || echo "nothing to commit"
        remote="https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
        branch="${GITHUB_REF:11}"
        git push "${remote}" ${branch} || echo "nothing to push"
      shell: bash
